version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:8.2-apache
    steps:
      - run:
          name: Install system packages
          command: apt-get update -y && apt-get install -y libzip-dev zip unzip git libicu-dev
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install zip pdo_mysql intl
      - run:
          name: WORKAROUND - detected dubious ownership
          command: git config --global --add safe.directory /var/www/html
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: PHPSTAN
          command: php composer.phar phpstan
      - run:
          name: CSFIXER
          command: php composer.phar csfixer